dns:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
  command: /go/bin/dnsdock -domain dc

activemq:
  image: rmohr/activemq
  user: root
  restart: always
  ports:
    - 61616:61616
    - 8616:8616
    - 8116:8116
  dns: 172.17.42.1
  volumes:
    - src/main/resources/activemq/conf:/etc/activemq/conf:ro
  environment:
    ACTIVEMQ_CONF: /etc/activemq/conf
    ACTIVEMQ_DATA: /var/lib/activemq/data
    DNSDOCK_ALIAS: activemq.dc

camelot1:
  extends:
    file: common-services.yml
    service: camelot
  ports:
    - 18081:18082
  environment:
    DNSDOCK_ALIAS: camelot1.dc

camelot2:
  extends:
    file: common-services.yml
    service: camelot
  ports:
    - 18082:18082
  environment:
    DNSDOCK_ALIAS: camelot2.dc

mongodb1:
  image: mongo:latest
  expose:
    - 27017:27017
  dns: 172.17.42.1
  command: /usr/bin/mongod --replSet sandbox --smallfiles
  environment:
    DNSDOCK_ALIAS: mongodb1.dc

mongodb2:
  image: mongo:latest
  expose:
    - 27017:27017
  dns: 172.17.42.1
  command: /usr/bin/mongod --replSet sandbox --smallfiles
  environment:
    DNSDOCK_ALIAS: mongodb2.dc

mongodb3:
  image: mongo:latest
  expose:
    - 27017:27017
  dns: 172.17.42.1
  command: /usr/bin/mongod --replSet sandbox --smallfiles
  environment:
    DNSDOCK_ALIAS: mongodb3.dc

mongoinit:
  image: tutum/mongodb:latest
  dns: 172.17.42.1
  volumes:
    - src/main/resources/mongodb:/etc/mongodb:ro
  command: /bin/bash /etc/mongodb/init.sh
