dns:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
  command: /go/bin/dnsdock -domain dc

camelot:
  extends:
    file: common-services.yml
    service: camelot
  ports:
    - 18081:18082
  environment:
    DNSDOCK_ALIAS: camelot.dc

rabbitmq1:
  extends:
    file: common-services.yml
    service: rabbitmq
  hostname: rabbitmq1
  environment:
    DNSDOCK_ALIAS: 'rabbitmq1.dc'
    RABBITMQ_NODENAME: rabbit

rabbitmq2:
  extends:
    file: common-services.yml
    service: rabbitmq
  hostname: rabbitmq2
  environment:
    DNSDOCK_ALIAS: 'rabbitmq2.dc'
    RABBITMQ_NODENAME: rabbit

